from models import ScheduledEvent
from sqlalchemy.ext.asyncio import AsyncSession
import logging
from notification_service import send_push_notification

logger = logging.getLogger(__name__)

async def handle_event(event: ScheduledEvent, db: AsyncSession):
    """
    Handles any scheduled event using the Agent-First "Pre-Generated" pattern.
    The content (title/body) was already generated by the Agent when the timer was set.
    """
    logger.info(f"Handling event {event.id} type={event.event_type}")

    # 1. Extract Pre-Generated Content
    # Default fallback if payload is missing specific keys
    payload = event.payload or {}
    title = payload.get("title", "Check-in")
    body = payload.get("body", "Time to check in!")
    
    # 2. Add extra data for the app to generic
    data = {"type": event.event_type, "payload": event.payload}

    # 3. Deliver the Agent's Message
    await send_push_notification(event.user_id, title, body, data)
