"""add_cron_job_id_to_events

Revision ID: a649a935709e
Revises: 3ca09e08a565
Create Date: 2026-02-04 16:12:01.523490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a649a935709e'
down_revision: Union[str, Sequence[str], None] = '3ca09e08a565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_events', sa.Column('cron_job_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_events', 'cron_job_id')
    # ### end Alembic commands ###
